/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.Chat.app;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void runSystemDoesNotThrow() {
        App classUnderTest = new App();
        assertDoesNotThrow(() -> classUnderTest.runSystem(), "runSystem should not throw any exceptions");
    }
}