/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.Chat.app;

import com.example.Chat.app.Admin.AdminUI;

public class App {
    public void runSystem(){
        // Create and display the AdminUI form
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AdminUI().setVisible(true);
            }
        });
    }

    public static void main(String[] args) {
        new App().runSystem();
    }
}
